package com.microfinance.wallet.domain.model;
public enum TransactionType {
    DEPOSIT, WITHDRAWAL, TRANSFER, PAYMENT, LOAN_DISBURSEMENT, LOAN_REPAYMENT,
    SAVINGS_DEPOSIT, SAVINGS_WITHDRAWAL, REVERSAL, FEE, INTEREST, REFUND, AIRTIME_PURCHASE
}