#!/bin/bash
set -e

# Create multiple databases
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE auth_db;
    CREATE DATABASE user_db;
    CREATE DATABASE kyc_db;
    CREATE DATABASE wallet_db;
    CREATE DATABASE payment_db;
    CREATE DATABASE loan_db;
    CREATE DATABASE savings_db;
    CREATE DATABASE cooperative_db;
    CREATE DATABASE agent_db;
    CREATE DATABASE credit_db;
    CREATE DATABASE reporting_db;
    CREATE DATABASE admin_db;
    CREATE DATABASE audit_db;
    CREATE DATABASE fraud_db;
    CREATE DATABASE offline_sync_db;
    CREATE DATABASE voice_db;

    GRANT ALL PRIVILEGES ON DATABASE auth_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE user_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE kyc_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE wallet_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE payment_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE loan_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE savings_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE cooperative_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE agent_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE credit_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE reporting_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE admin_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE audit_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE fraud_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE offline_sync_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE voice_db TO $POSTGRES_USER;
EOSQL

echo "All databases created successfully!"
