apiVersion: v1
kind: ConfigMap
metadata:
  name: microfinance-config
  namespace: microfinance
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  EUREKA_URL: "http://discovery-server:8761/eureka/"
  CONFIG_SERVER_URL: "http://config-server:8888"
  KAFKA_SERVERS: "kafka:9092"
  DB_HOST: "postgres"
  DB_USER: "postgres"
  REDIS_HOST: "redis"
  MONGODB_HOST: "mongodb"
  MINIO_ENDPOINT: "http://minio:9000"
  JAVA_OPTS: "-XX:MaxRAMPercentage=75 -XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom"
